### ISSUE TITLE
Sign-up strategy

### ISSUE THREAD

**Issue by pierrealixt** [kartoza/ford3#122]
In order to avoid bad and irrelevant data, we must disable public sign up.

For each provider interested in using the app, Kartoza will create (using the admin site):
- a new provider (only its name, e.g: False Bay College)
- a new user attached to this provider:
  - username: user email (e.g: jean@falsebaycollege.co.za)

An activation email will be sent to the user. He will have to choose a password.
Then he'll be able to fill up details about the provider, create the campus and create campus users.

Kartoza will not create campus users. The provider user must do it. 
Only an email address is required. 
An activation email will be sent to this new campus user, he will have to choose password then he'll be able to fill up details about his campus.

@timlinux @lucernae  Does this strategy make sense for you?

--
At some point, Kartoza will have to detach itself from the sign-up process. 
We should not own the right to accept/deny a provider. 
Likely, it will be someone like Ismael (?) at the WCED for the Western Province.

**Comment by lucernae** [comment]
@pierrealixt Yes, I agree this should be an invitation-only sign up process.
