### ISSUE TITLE
style the campus-qualification form

### ISSUE THREAD

**Issue by pierrealixt** [kartoza/ford3#146]
<img width="926" alt="Screen Shot 2019-04-01 at 10 22 11" src="https://user-images.githubusercontent.com/35932320/55313435-0e9ccd80-5468-11e9-9121-2c547ac9b879.png">

**Comment by boney-bun** [comment]
initial work:
![ford3#146](https://user-images.githubusercontent.com/4602383/55349320-970c8400-54e3-11e9-9381-15b23a79b7bf.gif)

any comments?
still need to be polished:
- *All* tab
- how to fetch and divide the list of qualifications into sub lists
- breadcrumbs with the *>* shape at the right of each steps are likely to require fixed size background. hence, it will be difficult to maintain for many different screen sizes. i prefer to keep it in a rectangular. what do you think?

**Comment by pierrealixt** [comment]
Nice @boney-bun 
Open a PR with your work and we'll continue the discussion there.

Do not bother about the _All_ or the _Recommend_ tab.
Do not bother as well for the sublists. We don't have them yet.
Do not bother as weel for the breadcrumbs, it is not a big problem.

I want you to style the list of qualifications (font-size, color, color of the link)
You should set the right div to `overflow: scroll`.
Style:
- the button `clear`
- a selected element
