### ISSUE TITLE
new action: add events

### ISSUE THREAD

**Issue by pierrealixt** [kartoza/ford3#154]
See mockup 'Campus Form - Important Dates'.
The mockup is not correct: it should only have one button 'add another event'.
When clicked, it should show three new inputs:
- event name (text)
- event date (date
- http link to event (text)

**Comment by Christiaanvdm** [comment]
![image](https://user-images.githubusercontent.com/34506346/55478466-12715100-561c-11e9-9100-4a1bc9a37752.png)

**Comment by Christiaanvdm** [comment]
See Dimas' qualification subjects
