### ISSUE TITLE
We need to organise focus group meetings

### ISSUE THREAD

**Issue by timlinux** [kartoza/ford3#16]
PROBLEM
-We need to organise focus group meetings to get end user inputs

SOLUTION
-Capture the whiteboard drawings in Graffle
-Identify a school/schools(s) where we can talk to the LO teacher/students - -speak to March as Ismail is probably very busy
-Compile some discussion questions for teachers and students

**Comment by AlwynSmit** [comment]
Meeting scheduled with P-A & Carina 14:30 6 Nov to discuss the approach

**Comment by AlwynSmit** [comment]
Current approach captured in description
