### ISSUE TITLE
sidebar doesn't go to the bottom of the page

### ISSUE THREAD

**Issue by pierrealixt** [kartoza/ford3#185]
![sidebar-height-bug](https://user-images.githubusercontent.com/35932320/55555625-fdf98b00-56e5-11e9-8a8b-cda63b60d493.gif)

the following css might the issue
```
html, body, .wrapper {
  height: 100%
}
```

**Comment by pierrealixt** [comment]
I re-open this issue as it is not solved.
<img width="847" alt="Screen Shot 2019-04-11 at 15 28 39" src="https://user-images.githubusercontent.com/35932320/55962470-39113680-5c71-11e9-8e9f-1cda508bde6b.png">

**Comment by boney-bun** [comment]
it's because the content doesn't enough to fill in the window's height.

we could set the height to be equal to window's height, but the side effect is we need adding vertical scroll for other contents with heights more than window's height.
