### ISSUE TITLE
Establish contacts for discussion groups

### ISSUE THREAD

**Issue by AlwynSmit** [kartoza/ford3#19]
Need to identify key school(s)/teacher(s) that can be approached for a discussion(s) on how they would like to use the app

child of #16

**Comment by AlwynSmit** [comment]
Fired off an email to March

**Comment by pierrealixt** [comment]
Find a school in western cape:
https://wcedemis.westerncape.gov.za/wced/findaschool.html

Have a look at the search. There are a lot of good information about schools (language of teaching, Principal's name, school fees, male/female ratio, learners per subject, number of learners per classroom)

**Comment by Vries14** [comment]
Contact details for Cloetesville H.S,  public school in Stellenbosch
 021-8895424
