### ISSUE TITLE
wrong combination of providers, campus, and qualifications should return error message

### ISSUE THREAD

**Issue by boney-bun** [kartoza/ford3#222]
# Problem
the url for a provider, campuses and qualifications are a combination of numbers supplied with a specific pattern.

a knowledgeable user may try changing the url manually.
it still work, but show invalid info.

for example:
- provider 1, campus 1 may have url like: *<host>/ford3/providers/1/campus/1*
- provider 2, campus 2 may have url like: *<host>/ford3/providers/2/campus/2*

a user can try: *<host>/ford3/providers/1/campus/2*

the server will return info about Provider 2 and Campus 2

# Solution
Add filter so an invalid url combination should return error message saying something like: "the campus does not exist".

**Comment by Christiaanvdm** [comment]
Good catch!

**Comment by pierrealixt** [comment]
This will be fixed when we'll have the users and permissions.
