### ISSUE TITLE
We need to implement the django models for the data model

### ISSUE THREAD

**Issue by timlinux** [kartoza/ford3#26]
![schema](https://user-images.githubusercontent.com/178003/50773558-d4bd9000-1299-11e9-819f-d0ccec15fe6c.png)

This is the general schema we will implement. We are awaiting feedback from March and Jason, but pending that feedback I think we should already start building the models for it.

**Comment by timlinux** [comment]
Child of #25

**Comment by timlinux** [comment]
Depends on #8

**Comment by timlinux** [comment]
@pierrealixt I have reassigned this to @Christiaanvdm

**Comment by pierrealixt** [comment]
![OpenEducationSchemaAndArchitecture_v3_20190115.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b30a1407a567800129bc06d/125516c66e82c728ace21e0d46c7849f2da787bc8ce8ab4aab53c39721432a72080aa70a6286eb21ab4778151a1d1bc3075b3046fcf8802ba7b73962964e4baf8e370a27822f1bbebdd04be954b929df1e87b3eede19c0e83874e38fde196f1717049bbd0c6bf4c6169112a309f34747a5143c62e372317a45971f752c626e2fb9b1.png)
