### ISSUE TITLE
Do we need this alert box?

### ISSUE THREAD

**Issue by pierrealixt** [kartoza/ford3#271]
<img width="677" alt="Screen Shot 2019-04-26 at 17 54 58" src="https://user-images.githubusercontent.com/35932320/56820543-846c3d00-684c-11e9-833f-b9faec21f585.png">

I kinda feel it breaks the workflow. 
@Christiaanvdm What did you add it in the first place?

**Comment by Christiaanvdm** [comment]
Not anymore - at some point in time I was pressing enter and submitting the form by accident (something in the UI prompted me to) but the UI no longer has me doing that.
