### ISSUE TITLE
the qualification page has not fully populated yet

### ISSUE THREAD

**Issue by boney-bun** [kartoza/ford3#287]
# Problem

the qualifications page has 5 sections.
the last three sections, namely *Requirements*, *Interests and Jobs*, and *Important Dates*, are not fully developed yet.
from the qualification page:
![Screen Shot 2019-05-02 at 12 32 15 PM](https://user-images.githubusercontent.com/4602383/57057905-6ed89680-6cd6-11e9-9153-a84d2b437502.png)

when click on edit page, it will redirect to a new edit page. 
i have filled in all those info before. 
however, the existing info doesn't get populated.

# Solution
- ensure the business logic for these 3 sections
- the layout of these sections should follow the mockup.

**Comment by pierrealixt** [comment]
@boney-bun 
The qualification events do exist in the db.
Same for the interests and jobs.
