### ISSUE TITLE
Sidebar doesn't go to the bottom of the page

### ISSUE THREAD

**Issue by pierrealixt** [kartoza/ford3#297]
![bug-sidebar-height](https://user-images.githubusercontent.com/35932320/57071700-941bd380-6cdb-11e9-81c1-e0639e13144a.gif)

**Comment by boney-bun** [comment]
@pierrealixt do we want to make the sidebar like: https://getbootstrap.com/docs/4.3/examples/dashboard/ as you mentioned in #223

**Comment by pierrealixt** [comment]
yes @boney-bun
