### ISSUE TITLE
Review orchestration

### ISSUE THREAD

**Issue by pierrealixt** [kartoza/ford3#46]
See 
https://github.com/kartoza/ford3/pull/38

**Comment by lucernae** [comment]
I will first write here my review goals/milestone so everyone can comment on it and tell me if I'm going overboard :p.

Target Milestone:
- [x] Use ansible setup project generation, so local development environment can be quickly generated/changed
- [x] Docker-compose.yml file will contain production grade configuration for manual docker deployment in one host
- [x] Docker-compose.override.yml file will contain user overrides for local development. This is generated by ansible setup, and excluded from git repo.
- [x] PyCharm project settings for deployment will be auto generated (can also be turned off)
- [x] Makefile will use proper docker-compose namespacing and commands whenever possible. We will avoid to refer the container directly using `docker` command
- [x] Migrate docker-compose to v2 or v2.1, whichever compatible with Rancher
- [x] Deprecate manual build/deploy of prod images. Or perhaps modify it to also work in complement with trigger build setup.
- [x] Use official nginx image. Configure the forwarding with sites-enabled.

**Comment by pierrealixt** [comment]
Same setup as ScanAgroEmpresa?

**Comment by lucernae** [comment]
Yes

**Comment by lucernae** [comment]
Update:
- The make command `make dbsnapshot` needs to docker cp from running containers. At the moment, docker-compose doesn't have a cp command. So, we have to specify the container name at the moment. There are `docker ps` filters to filter out db container name, but it's also a hack. So we just use the easiest one for now.

**Comment by lucernae** [comment]
Done all the above now.
