### ISSUE TITLE
Check deployment strategy

### ISSUE THREAD

**Issue by pierrealixt** [kartoza/ford3#50]
DockerHub?
TeamCity?
Through Travis?

**Comment by lucernae** [comment]
Our (planned) deployment strategy now.

1. Submit PR, CI will check if it is ok [TODO]
2. PR merged, trigger teamcity docker build [Done]
3. Teamcity push new docker image to public registry (DockerHub) [Done]
4. Teamcity contact Rancher API to upgrade image in testing server [Done]

**Comment by pierrealixt** [comment]
@lucernae 
Which CI do we use? Travis? is it configured?

**Comment by lucernae** [comment]
@pierrealixt it's Travis. I think we can close this. Since we already merged Travis config.
