### ISSUE TITLE
Integrate Campus Details form (1/4)

### ISSUE THREAD

**Issue by pierrealixt** [kartoza/ford3#51]

**Comment by lucernae** [comment]
required by #54

**Comment by lucernae** [comment]
<img width="1043" alt="Screen Shot 2019-03-18 at 17 27 03" src="https://user-images.githubusercontent.com/831865/54523862-10b05800-49a3-11e9-8524-42a6bf91bccc.png">

Some note on the implementation:

We have to change the model from `photo_url` to just `photo` and use a `FileField`

Tasks:
- [ ] Generate correct DOM from model field
- [ ] Use FileField for `photo` of Campus
- [ ] Add validation for tel number, and email

CC @pierrealixt @Christiaanvdm
