### ISSUE TITLE
Interests

### ISSUE THREAD

**Issue by pierrealixt** [kartoza/ford3#586]
Maybe we could have two interests per row?

![IMG_02DD8FAA32AB-1](https://user-images.githubusercontent.com/35932320/59448815-3d3f0900-8e06-11e9-8544-14a2bb5e928a.jpeg)

**Comment by Christiaanvdm** [comment]
The signal row should only be for the mega extremes in terms of device sizes. Unless I am mistaken there are exceptionally few devices (2, to be precise) smart devices with < 480 pixels (width or height). I would need to define more media widths than bootstrap supplies I believe.

![image](https://user-images.githubusercontent.com/34506346/60017979-578ca880-968a-11e9-8d11-1ae2a2909876.png)
