### ISSUE TITLE
We need to develop the project branding profile

### ISSUE THREAD

**Issue by timlinux** [kartoza/ford3#6]
Stanard colours and swatch board of fonts etc to be used for the project

**Comment by carina1000** [comment]
@timlinux is this 'ready'? Won't this depend on whether we co-brand with, say, an aptitude test provider?

**Comment by carina1000** [comment]
Please refer to suggested style guide:

[EduOpen.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46cd908f0c9286a7cda5fd53b652fa912a5265296b51a12f7680b071bb4329540d0b1bac415d0e40f8a8df7aafa42062c80d55b98e30063e937f03a6aa8316b500bf248e4682b4b98a4ac0ec3f37aa.pdf)
