### ISSUE TITLE
Low fidelity mockups for the Provider-UI

### ISSUE THREAD

**Issue by timlinux** [kartoza/ford3#7]

**Comment by timlinux** [comment]
We need to break this down into subtickets for the key functional areas of the web site.

**Comment by pierrealixt** [comment]
https://docs.google.com/presentation/d/1muatHbRIAjypmT_MQLpu6iVaKdjAP2UEeKchKOGT7v4/edit#slide=id.p


Define the user journey.
Think about the multi-step form (break down information we want by page).
